name: Update mods
on:
  # Triggers the workflow every 2 hours
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
 
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Execute update check
        run: |
            echo "SUCCESS=false" >> $GITHUB_ENV
            node index.js
            if [ "$?" = 0 ]; then echo "SUCCESS=true" >> $GITHUB_ENV; fi
      - name: Commit back cache file
        if: ${{ env.SUCCESS }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
            file_pattern: 'cache.json'
            commit_message: 'Update modpack cache'
      - name: Create release
        if: ${{ env.SUCCESS }}
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          fail_on_unmatched_files: true
          files: modpack.zip
